### ISSUE TITLE
Salut 

### ISSUE THREAD

**Issue by Daniel-arc** [vb6rocod/hddlinks_android#1]
Am incercat instalarea pe un media player mxq dar nu funcționează nu găsește serverul și nici php 5 nu găsește doar 7.2 ți-am lăsat și pe email ceva mesaje

**Comment by vb6rocod** [comment]
Persoana care a facut Server for php nu mai ofera suport, asa ca pachetele de instalare pentru alte versiuni php nu mai sunt disponibile.
Din fericire am avut salvat pachetul pentru php 5.6.35.  Ca urmare am facut o versiune de server cu php 5.6.35 si in plus am adaugat si fisierele de script pentru rularea aplicatiei.
Descarcati si instalati: Server_for_PHP_HD4ALL_nou.apk
https://www.mediafire.com/file/6mnyumjp0e9xhqj/Server_for_PHP_HD4ALL_nou.apk/file

**Comment by Daniel-arc** [comment]
Va mulțumesc bună treabă că doresc multa sănătate și sărbători fericite

Trimis din Yahoo Mail pe Android 
 
  Pe Dum, dec. 1, 2019 la 22:19, vb6rocod<notifications@github.com> a scris:   
Persoana care a facut Server for php nu mai ofera suport, asa ca pachetele de instalare pentru alte versiuni php nu mai sunt disponibile.
Din fericire am avut salvat pachetul pentru php 5.6.35. Ca urmare am facut o versiune de server cu php 5.6.35 si in plus am adaugat si fisierele de script pentru rularea aplicatiei.
Descarcati si instalati: Server_for_PHP_HD4ALL_nou.apk
https://www.mediafire.com/file/6mnyumjp0e9xhqj/Server_for_PHP_HD4ALL_nou.apk/file
